server:
  port: 6688
  servlet:
    context-path: /gen

spring:
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  typeAliasesPackage: cn.hfbin.gen.*.entity
  global-config:
    banner: false
    #原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

libra:
  mybatisPlus:
    openTenant: false
