server:
  port: 7825
  servlet:
    context-path: /ucpm

spring:
  profiles:
    active: dev
    include: sentinel
  main:
    allow-bean-definition-overriding: true


libra:
  mybatisPlus:
    ignoreTable: ucpm_datasource_conf,ucpm_interface,ucpm_menu,ucpm_menu_interface_ref,ucpm_version,ucpm_client
    openTenant: true

logging:
  level:
    cn.hfbin: info

# prometheus
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}