CREATE DATABASE `libra-base` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
CREATE DATABASE `libra-gen` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
CREATE DATABASE `libra-tr` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
CREATE DATABASE `libra-ucpm` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
CREATE DATABASE `nacos` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;